services:
  elasticsearch:
    container_name: DrLink.ElasticSearch
    image: elasticsearch:7.17.25
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - ELASTIC_PASSWORD=Dev1234
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - drlink_network

  kibana:
    container_name: DrLink.Kibana
    image: kibana:7.17.25
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://DrLink.ElasticSearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Dev1234
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - drlink_network

  redis:
    container_name: DrLink.Redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "Heli@ghar771379"
    networks:
      - drlink_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Heli@ghar771379", "ping"]
      interval: 30s
      retries: 3
      timeout: 10s

  mysql:
    image: mysql:latest
    container_name: DrLink.Mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: drlinkP
      MYSQL_USER: drlinkadmin
      MYSQL_PASSWORD: 123456789a
      MYSQL_ROOT_PASSWORD: 123456789a
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --bind-address=0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - drlink_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p123456789a",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: DrLink.PhpMyAdmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 123456789a
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - drlink_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: DrLink.SqlServer
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Hello&Run1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    restart: always
    networks:
      - drlink_network

  postgres:
    image: postgres:latest
    container_name: DrLink.Postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: drlinkdb
      POSTGRES_USER: drlinkadmin
      POSTGRES_PASSWORD: 123456789a
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - drlink_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "drlinkadmin"]
      interval: 30s
      retries: 3
      timeout: 10s

volumes:
  mysql_data:
    driver: local
  esdata:
    driver: local
  postgres_data:
    driver: local

networks:
  drlink_network:
    name: drlink_network
    driver: bridge
